### ISSUE TITLE
The validates a valid chain test is failing 

### ISSUE THREAD

**Issue by chankruze** [geekofia/coin#1]
jest is saying block undefined ... 

https://github.com/geekofia/coin/blob/ec4b69ca5237ad70b94fec67bb13369f7edf1667/blockchain.js#L15-L32

```
 PASS  ./block.test.js
 FAIL  ./blockchain.test.js
  ● Blockchain › validates a valid chain

    TypeError: Cannot read property 'lastHash' of undefined

      23 |             const lastBlock = chain[i - 1];
      24 | 
    > 25 |             if (block.lastHash !== lastBlock.hash ||
         |                       ^
      26 |                 block.hash !== Block.blockHash(block)) {
      27 |                 return false;
      28 |             }

      at Blockchain.lastHash [as isValidChain] (blockchain.js:25:23)
      at Object.isValidChain (blockchain.test.js:31:19)

Test Suites: 1 failed, 1 passed, 2 total
Tests:       1 failed, 6 passed, 7 total
Snapshots:   0 total
Time:        1.867s
Ran all test suites.

```

**Comment by chankruze** [comment]
If added console log to log block, it indeed prints block object but why it is saying undefined in for loop then ?

```
 PASS  ./block.test.js
 FAIL  ./blockchain.test.js
  ● Console

    console.log blockchain.js:23
      Block {
        timestamp: 1563020441084,
        lastHash: 'f1r57-h45h',
        hash:
         'c3720a6043946d3829bb0c9aa8face236aabbd544d5ea426d0efd6ee6357afbd',
        data: 'foo' }
    console.log blockchain.js:25
      Block {
        timestamp: 'Genesis time',
        lastHash: '-------',
        hash: 'f1r57-h45h',
        data: [] }
    console.log blockchain.js:23
      undefined
    console.log blockchain.js:25
      Block {
        timestamp: 1563020441084,
        lastHash: 'f1r57-h45h',
        hash:
         'c3720a6043946d3829bb0c9aa8face236aabbd544d5ea426d0efd6ee6357afbd',
        data: 'foo' }
    console.log blockchain.js:23
      Block {
        timestamp: 1563020441111,
        lastHash: 'f1r57-h45h',
        hash:
         '467fd31d17e7360c39dd8df3c54f4119cd218816781331fd7152b202620d0687',
        data: 'Not foo' }
    console.log blockchain.js:25
      Block {
        timestamp: 'Genesis time',
        lastHash: '-------',
        hash: 'f1r57-h45h',
        data: [] }

  ● Blockchain › validates a valid chain

    TypeError: Cannot read property 'lastHash' of undefined

      25 |             console.log(lastBlock);
      26 | 
    > 27 |             if (block.lastHash !== lastBlock.hash ||
         |                       ^
      28 |                 block.hash !== Block.blockHash(block)) {
      29 |                 return false;
      30 |             }

      at Blockchain.lastHash [as isValidChain] (blockchain.js:27:23)
      at Object.isValidChain (blockchain.test.js:31:19)

Test Suites: 1 failed, 1 passed, 2 total
Tests:       1 failed, 6 passed, 7 total
Snapshots:   0 total
Time:        1.949s
Ran all test suites.
```

**Comment by chankruze** [comment]
```
const block = chain[i];
console.log(block.lastHash);
const lastBlock = chain[i - 1];
console.log(lastBlock.hash);
```
```
 PASS  ./block.test.js
 FAIL  ./blockchain.test.js
  ● Console

    console.log blockchain.js:23
      f1r57-h45h
    console.log blockchain.js:25
      f1r57-h45h
    console.log blockchain.js:23
      f1r57-h45h
    console.log blockchain.js:25
      f1r57-h45h

  ● Blockchain › validates a valid chain

    TypeError: Cannot read property 'lastHash' of undefined

      21 |         for (let i = 1; 1 < chain.length; i++) {
      22 |             const block = chain[i];
    > 23 |             console.log(block.lastHash);
         |                               ^
      24 |             const lastBlock = chain[i - 1];
      25 |             console.log(lastBlock.hash);
      26 | 

      at Blockchain.lastHash [as isValidChain] (blockchain.js:23:31)
      at Object.isValidChain (blockchain.test.js:31:19)

Test Suites: 1 failed, 1 passed, 2 total
Tests:       1 failed, 6 passed, 7 total
Snapshots:   0 total
Time:        2.961s
Ran all test suites.
```

**Comment by chankruze** [comment]
All it was a simple typo :(
